// Generated by build-timeline.mjs --types from script.json. Do not edit.
import type { FilmProps } from "../kit";
export type SceneId = "subject" | "forms" | "artifact" | "gates" | "cite" | "holds" | "prose" | "handoff";
export type SourceId = "check";
export type Props = FilmProps<SceneId, SourceId>;
